<?php

use App\Http\Controllers\AssessmentController;
use Illuminate\Support\Facades\Route;

Route::get('/', [AssessmentController::class, 'dashboard'])->name('dashboard');
Route::get('/dashboard', [AssessmentController::class, 'dashboard']);
Route::get('/assessment', [AssessmentController::class, 'show'])->name('assessment.show');
Route::post('/assessment/score', [AssessmentController::class, 'score'])->name('assessment.score');
Route::post('/dashboard/ai', [AssessmentController::class, 'dashboardAi'])->name('dashboard.ai');
Route::get('/resources', [AssessmentController::class, 'resources'])->name('resources');
Route::get('/tools/support-navigator', [AssessmentController::class, 'supportNavigator'])->name('tools.navigator');
Route::get('/tools/daily-check-in', [AssessmentController::class, 'dailyCheckIn'])->name('tools.checkin');
Route::post('/tools/daily-check-in/ai', [AssessmentController::class, 'dailyCheckInAi'])->name('tools.checkin.ai');
Route::get('/tools/goal-builder', [AssessmentController::class, 'goalBuilder'])->name('tools.goal');
Route::get('/tools/daily-planner', [AssessmentController::class, 'dailyPlanner'])->name('tools.planner');
Route::get('/tools/time-block', [AssessmentController::class, 'timeBlock'])->name('tools.time');
Route::get('/tools/body-needs', [AssessmentController::class, 'bodyNeeds'])->name('tools.body');
Route::get('/tools/medication-refill', [AssessmentController::class, 'medicationRefill'])->name('tools.meds');
Route::get('/tools/food-rescue', [AssessmentController::class, 'foodRescue'])->name('tools.food');
Route::get('/tools/sleep-wind-down', [AssessmentController::class, 'sleepWindDown'])->name('tools.sleep');
Route::get('/tools/motivation-menu', [AssessmentController::class, 'motivationMenu'])->name('tools.motivation');
Route::get('/tools/wins-log', [AssessmentController::class, 'winsLog'])->name('tools.wins');
Route::get('/tools/accountability', [AssessmentController::class, 'accountability'])->name('tools.accountability');
Route::get('/tools/routine-builder', [AssessmentController::class, 'routineBuilder'])->name('tools.routine');
Route::get('/tools/weekly-reset', [AssessmentController::class, 'weeklyReset'])->name('tools.weekly');
Route::get('/tools/communication-repair', [AssessmentController::class, 'communicationRepair'])->name('tools.communication');
Route::get('/tools/energy-crash', [AssessmentController::class, 'energyCrash'])->name('tools.energy');
Route::get('/tools/decision-priority', [AssessmentController::class, 'decisionPriority'])->name('tools.decision');
Route::get('/tools/focus-sprint', [AssessmentController::class, 'focusSprint'])->name('tools.focus');
Route::get('/tools/emotional-reset', [AssessmentController::class, 'emotionalReset'])->name('tools.emotion');
Route::get('/tools/safety-pause', [AssessmentController::class, 'safetyPause'])->name('tools.safety');
Route::get('/tools/transition-rescue', [AssessmentController::class, 'transitionRescue'])->name('tools.transition');
Route::get('/tools/appointment-prep', [AssessmentController::class, 'appointmentPrep'])->name('tools.appointment');
Route::get('/tools/care-notes', [AssessmentController::class, 'careNotes'])->name('tools.care');
Route::get('/tools/support-request', [AssessmentController::class, 'supportRequest'])->name('tools.support');
Route::get('/tools/work-school-support', [AssessmentController::class, 'workSchoolSupport'])->name('tools.workschool');
Route::get('/tools/job-hunt', [AssessmentController::class, 'jobHunt'])->name('tools.job');
Route::get('/tools/home-reset', [AssessmentController::class, 'homeReset'])->name('tools.home');
Route::get('/tools/laundry-rescue', [AssessmentController::class, 'laundryRescue'])->name('tools.laundry');
Route::get('/tools/digital-clutter', [AssessmentController::class, 'digitalClutter'])->name('tools.digital');
Route::get('/tools/money-admin', [AssessmentController::class, 'moneyAdmin'])->name('tools.money');
Route::get('/tools/aid-application', [AssessmentController::class, 'aidApplication'])->name('tools.aid');
Route::get('/tools/lost-item', [AssessmentController::class, 'lostItem'])->name('tools.lost');
Route::get('/tools/errand-launch', [AssessmentController::class, 'errandLaunch'])->name('tools.errand');
Route::get('/tools/provider-shortlist', [AssessmentController::class, 'providerShortlist'])->name('tools.providers');
Route::get('/tools/access-plan', [AssessmentController::class, 'accessPlan'])->name('tools.access');
Route::get('/tools/task-breakdown', [AssessmentController::class, 'taskBreakdown'])->name('tools.task');
Route::get('/tools/follow-up-rescue', [AssessmentController::class, 'followUpRescue'])->name('tools.followup');
Route::get('/tools/reminders', [AssessmentController::class, 'reminders'])->name('tools.reminders');
Route::get('/tools/symptom-tracker', [AssessmentController::class, 'symptomTracker'])->name('tools.tracker');
